name: Checkout Code 
on: [push] #triggers 
jobs: 
   build: #these should be unique 
    runs-on: ubuntu-latest #Linux OS. we can have windows or mac 
    steps: #stages 
   # checkout will happen here 
     - name: checkout 
       uses: actions/checkout@v5 
     - name: display the files 
       run: ls -la   